### ISSUE TITLE
Price not showing up

### ISSUE THREAD

**Issue by eschiendorfer** [thirtybees/elasticsearch#33] opened 2017-10-24 16:14 UTC
For me there is no price showing up, after searching.

![search-result](https://user-images.githubusercontent.com/15154932/31954802-d5e5fade-b8e6-11e7-92df-e4c4d4d57591.JPG)

I believe the wrong look is because of my theme. But the price should be there anyway!?

Version: 1.0.3, PHP 7.0.24, MySQL 10.2.8-MariaDB

**Comment by firstred** [comment] 2017-10-31 10:22
Marking as fixed, since we hotfixed this live on the test environment.

**Comment by firstred** [comment] 2017-10-31 10:23
The cause was some customer groups that weren't synced (and the module didn't fall back on the default group).

**Closed by firstred** 2017-10-31 10:22 UTC
