### ISSUE TITLE
Index speed

### ISSUE THREAD

**Issue by nicdnepr** [thirtybees/elasticsearch#64] opened 2019-03-27 09:00 UTC
How increase index speed?

**Comment by nicdnepr** [comment] 2019-03-27 14:26
https://github.com/thirtybees/elasticsearch/blob/master/classes/IndexStatus.php#L218
Looks its part of problems, why need create goods objects list?

**Comment by getdatakick** [comment] 2021-03-22 13:25
Closing as duplicate of issue #62

**Closed by getdatakick** 2021-03-22 13:25 UTC
Labels: bug

**Comment by Zengraph** [comment] 2021-03-29 10:06
You can close this issue, as the new version is really fast to index thousands of products !
