### ISSUE TITLE
"Amount of items indexed" not counting up

### ISSUE THREAD

**Issue by devnix** [thirtybees/elasticsearch#56] opened 2018-02-15 09:17 UTC
Hi there! We are trying to make the plugin work, but we are experiencing issues.

We have been able to connect the plugin with an Elasticsearch Docker instance, but the indexed items counter is not working, and there are no logs from the plugin. I have checked the Elasticsearch logs and founded the following logs

```
[2018-02-15T09:10:49,312][INFO ][o.e.c.m.MetaDataDeleteIndexService] [EKZkTij] [thirtybees_1_1/741Mm-ZwRzyjuoO55ojh0w] deleting index
[2018-02-15T09:10:49,469][INFO ][o.e.c.m.MetaDataCreateIndexService] [EKZkTij] [thirtybees_1_1] creating index, cause [api], templates [], shards [2]/[2], mappings [product]
[2018-02-15T09:10:51,704][WARN ][o.e.d.c.x.s.AbstractXContentParser] Expected a boolean [true/false] for property [activeproperty] but got [1]
[2018-02-15T09:10:51,704][WARN ][o.e.d.c.x.s.AbstractXContentParser] Expected a boolean [true/false] for property [activeproperty] but got [1]
[2018-02-15T09:10:51,709][WARN ][o.e.d.c.x.s.AbstractXContentParser] Expected a boolean [true/false] for property [activeproperty_agg] but got [1]
[2018-02-15T09:10:51,709][WARN ][o.e.d.c.x.s.AbstractXContentParser] Expected a boolean [true/false] for property [activeproperty_agg] but got [1]
[2018-02-15T09:10:51,745][INFO ][o.e.c.m.MetaDataMappingService] [EKZkTij] [thirtybees_1_1/X8HsQMMRT0K_quCPGMkYFQ] update_mapping [product]
[2018-02-15T09:10:51,785][WARN ][o.e.d.c.x.s.AbstractXContentParser] Expected a boolean [true/false] for property [activeproperty] but got [1]
[2018-02-15T09:10:51,787][WARN ][o.e.d.c.x.s.AbstractXContentParser] Expected a boolean [true/false] for property [activeproperty_agg] but got [1]
[2018-02-15T09:10:51,793][WARN ][o.e.d.c.x.s.AbstractXContentParser] Expected a boolean [true/false] for property [activeproperty] but got [1]
[2018-02-15T09:10:51,794][WARN ][o.e.d.c.x.s.AbstractXContentParser] Expected a boolean [true/false] for property [activeproperty_agg] but got [1]
[2018-02-15T09:10:51,892][WARN ][o.e.d.c.x.s.AbstractXContentParser] Expected a boolean [true/false] for property [activeproperty] but got [1]
[2018-02-15T09:10:51,893][WARN ][o.e.d.c.x.s.AbstractXContentParser] Expected a boolean [true/false] for property [activeproperty_agg] but got [1]
[2018-02-15T09:10:51,897][WARN ][o.e.d.c.x.s.AbstractXContentParser] Expected a boolean [true/false] for property [activeproperty] but got [1]
[2018-02-15T09:10:51,899][WARN ][o.e.d.c.x.s.AbstractXContentParser] Expected a boolean [true/false] for property [activeproperty_agg] but got [1]
[2018-02-15T09:10:51,905][WARN ][o.e.d.c.x.s.AbstractXContentParser] Expected a boolean [true/false] for property [activeproperty] but got [1]
[2018-02-15T09:10:51,906][WARN ][o.e.d.c.x.s.AbstractXContentParser] Expected a boolean [true/false] for property [activeproperty_agg] but got [1]
[2018-02-15T09:10:51,916][WARN ][o.e.d.c.x.s.AbstractXContentParser] Expected a boolean [true/false] for property [activeproperty] but got [1]
[2018-02-15T09:10:51,918][WARN ][o.e.d.c.x.s.AbstractXContentParser] Expected a boolean [true/false] for property [activeproperty_agg] but got [1]
[2018-02-15T09:10:51,922][WARN ][o.e.d.c.x.s.AbstractXContentParser] Expected a boolean [true/false] for property [activeproperty] but got [1]
```

(and the list continues.)

If I inspect the XHR petitions on the plugin I get a lot of requests to `/index.php?controller=AdminModules&token=xxxxxxxxxxxxxxxxxxx&configure=elasticsearch&tab_module=front_office_features&module_name=elasticsearch&ajax=1&action=indexRemaining`, all of them with the following result.

```json
{
  "success":true,
  "indexed":0,
  "total":14841,
  "nbErrors":0,
  "errors":[]
}
```

Tried with 2.4.6 and 5.6.7 versions of Elasticsearch.

**Comment by doclucas** [comment] 2018-08-20 18:41
@DevNIX I have a similar (or maybe same issue) on a vanilla TB installation.
Were you able to find the solution?

Thank you

**Comment by DaoKakao** [comment] 2018-09-27 07:46
file classes/Fetcher.php, after line #377 i've inserted following code:
`if ($product->active ==='1') {
            $product->active = true;
        } else {
            $product->active = false;
        }
`
And indexing became working. The issue caused by reason because the product's 'active' property stored in the database as '1' or '0', while elasticsearch requires 'true' or 'false' without quotes.

**Comment by nicdnepr** [comment] 2019-03-27 08:03
Can use such code
`$product->active = boolval($product->active);`

**Comment by devnix** [comment] 2019-03-27 08:31
Sorry for the so much late answer, I never got it to work @doclucas.

Seems like it was referenced here, and closed: https://github.com/thirtybees/thirtybees/issues/754

Maybe this is working in a more recent version like 1.0.8? I'm not maintaining any ecommerce right now, and I'm a little bit busy to test it by myself.

If you report that it works with the latest version I will close this ticket @nicdnepr :-)

**Comment by nicdnepr** [comment] 2019-03-27 09:03
I got such error `failed to parse [activeproperty] Failed to parse value [1] as only [true] or [false] are allowed` when use elastic 6
In elastic 5 no error

**Comment by devnix** [comment] 2019-03-27 10:05
Ok, but what ThirtyBees version are you running?

**Comment by nicdnepr** [comment] 2019-03-27 10:10
Last version ThirtyBees and elasticsearch v1

**Comment by nicdnepr** [comment] 2019-03-27 12:24
@devnix btw what index speed you have? My speed is average 30 goods per second
You can answer here #64

**Comment by devnix** [comment] 2019-03-27 12:46
As I said before, I'm not working with any ecommerce right now.

**Comment by getdatakick** [comment] 2021-03-22 13:26
This issue should be fixed now

**Closed by getdatakick** 2021-03-22 13:26 UTC
Labels: bug
